name: Go crossbuild
description: Build Go applications for multiplatform and packaging with goxz
author: 'izumin5210'
inputs: 
  name:
    description: 'An application name'
    required: true
  arch:
    description: 'Space or comma separated list of GOARCH'
    default: 'amd64'
  dest:
    description: 'Path to destination directory of built binaries'
    default: './dist'
  ldflags:
    description: '`-ldflags` to pass to go build'
    default: ''
  tags:
    description: '`-tags` to pass to go build'
    default: ''
  os:
    description: 'Space or comma separated list of GOOS'
    default: 'darwin,linux,windows'
  package:
    description: 'Build target package'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.package }}
    - ${{ inputs.dest }}
    - ${{ inputs.arch }}
    - ${{ inputs.os }}
    - ${{ inputs.ldflags }}
    - ${{ inputs.tags }}
